# Make sure this file is included only once
get_filename_component(CMAKE_CURRENT_LIST_FILENAME ${CMAKE_CURRENT_LIST_FILE} NAME_WE)
if(${CMAKE_CURRENT_LIST_FILENAME}_FILE_INCLUDED)
  return()
endif()
set(${CMAKE_CURRENT_LIST_FILENAME}_FILE_INCLUDED 1)

set(proj niral_utilities)

set(${proj}_DEPENDENCIES ITKv4 SlicerExecutionModel VTK )

SlicerMacroCheckExternalProjectDependency(${proj})

ExternalProject_Add(${proj}
  SVN_REPOSITORY "https://www.nitrc.org/svn/niral_utilities/trunk"
  SVN_REVISION -r "42"
  SVN_USERNAME slicerbot
  SVN_PASSWORD slicer
  SOURCE_DIR ${proj}
  BINARY_DIR ${proj}-build
  DEPENDS ${${proj}_DEPENDENCIES}
  CMAKE_GENERATOR ${gen}
  CMAKE_ARGS
  ${CMAKE_OSX_EXTERNAL_PROJECT_ARGS}
  ${COMMON_EXTERNAL_PROJECT_ARGS}
  -DCOMPILE_CONVERTITKFORMATS:BOOL=ON
  -DCOMPILE_CROPTOOLS:BOOL=OFF
  -DCOMPILE_CURVECOMPARE:BOOL=OFF
  -DCOMPILE_DTIAtlasBuilder:BOOL=OFF
  -DCOMPILE_DWI_NIFTINRRDCONVERSION:BOOL=OFF
  -DCOMPILE_IMAGEMATH:BOOL=ON
  -DCOMPILE_IMAGESTAT:BOOL=OFF
  -DCOMPILE_POLYDATAMERGE:BOOL=OFF
  -DCOMPILE_POLYDATATRANSFORM:BOOL=OFF
  -DCOMPILE_TRANSFORMDEFORMATIONFIELD:BOOL=OFF
  -DITK_VERSION_MAJOR:STRING=${ITK_VERSION_MAJOR}
  -DITK_DIR:PATH=${ITK_DIR}
  -DGenerateCLP_DIR:PATH=${GenerateCLP_DIR}
  -DVTK_DIR:PATH=${VTK_DIR}
  ${cmakeversion_external_update} "${cmakeversion_external_update_value}"
  INSTALL_COMMAND ""
  )

